"""initial migration with all tables

Revision ID: 0a6daf3b7b4d
Revises:
Create Date: 2025-08-20 15:40:40.877491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6daf3b7b4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create merchants table first (referenced by merchant_tokens)
    op.create_table('merchants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('clover_merchant_id', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('clover_merchant_id')
    )
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)

    # Create merchant_detail table
    op.create_table('merchant_detail',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('clover_merchant_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('currency', sa.String(length=16), nullable=True),
        sa.Column('timezone', sa.String(length=64), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), onupdate=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('clover_merchant_id')
    )
    op.create_index(op.f('ix_merchant_detail_id'), 'merchant_detail', ['id'], unique=False)

    # Create merchant_tokens table (depends on merchants)
    op.create_table('merchant_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('merchant_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.Text(), nullable=False),
        sa.Column('token_type', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_tokens_id'), 'merchant_tokens', ['id'], unique=False)

    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('mobile_number', sa.String(length=15), nullable=False),
        sa.Column('otp', sa.String(length=6), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True, default=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('alternate_contact', sa.String(length=15), nullable=True),
        sa.Column('floor_or_office', sa.String(length=255), nullable=True),
        sa.Column('is_guest', sa.Boolean(), nullable=True, default=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), onupdate=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # Create otps table
    op.create_table('otps',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('mobile_number', sa.String(length=15), nullable=False),
        sa.Column('otp_code', sa.String(length=6), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False, default=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), onupdate=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop tables in reverse order (considering foreign key dependencies)
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')

    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')

    op.drop_index(op.f('ix_merchant_tokens_id'), table_name='merchant_tokens')
    op.drop_table('merchant_tokens')

    op.drop_index(op.f('ix_merchant_detail_id'), table_name='merchant_detail')
    op.drop_table('merchant_detail')

    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_table('merchants')

    # ### end Alembic commands ###
